services:
  frontoffice:
    build: 
      context: ../frontoffice 
      dockerfile: ../dev-config/Dockerfile.frontoffice
    container_name: astro_frontoffice
    restart: unless-stopped 
    ports:
      - "4321:4321"
    volumes:
      - ../frontoffice:/app
      - /app/node_modules
    networks:
      - strapi
  
  backoffice:
    build:
      context: ../backoffice
      dockerfile: ../dev-config/Dockerfile.backoffice
    container_name: strapi_backoffice
    restart: unless-stopped
    ports:
      - "1337:1337"
    volumes:
      - ../backoffice:/usr/app
      - /usr/app/node_modules
    environment:
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST} 
      APP_KEYS: ${APP_KEYS}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      NODE_ENV: ${NODE_ENV}
    depends_on:
      - db
    networks:
      - strapi
  
  db:
    image: postgres:14.1-alpine
    container_name: postgres_db
    restart: unless-stopped
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - strapi

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - strapi

  balancer:
    image: haproxy:2.8-alpine
    container_name: haproxy_balancer
    restart: unless-stopped
    ports:
      - "80:80"
      - "1936:1936"
    volumes:
      - ../balancer/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - backoffice
      - frontoffice
    networks:
      - strapi

networks:
  strapi:

volumes:
  db:
  pgadmin_data: