services:
  frontoffice-1:
    build: 
      context: ../frontoffice 
      dockerfile: ../dev-config/Dockerfile.frontoffice
    container_name: astro_frontoffice_1
    restart: unless-stopped
    volumes:
      - ../frontoffice:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4321"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - strapi

  frontoffice-2:
    build: 
      context: ../frontoffice 
      dockerfile: ../dev-config/Dockerfile.frontoffice
    container_name: astro_frontoffice_2
    restart: unless-stopped
    volumes:
      - ../frontoffice:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4321"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - strapi

  backoffice-1:
    build:
      context: ../backoffice
      dockerfile: ../dev-config/Dockerfile.backoffice
    container_name: strapi_backoffice_1
    restart: unless-stopped
    ports:
      - "1337:1337"
    volumes:
      - ../backoffice:/usr/app
      - /usr/app/node_modules
    environment:
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: db-1
      APP_KEYS: ${APP_KEYS}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      NODE_ENV: ${NODE_ENV}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1337/admin"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - strapi

  backoffice-2:
    build:
      context: ../backoffice
      dockerfile: ../dev-config/Dockerfile.backoffice
    container_name: strapi_backoffice_2
    restart: unless-stopped
    ports:
      - "1338:1337"
    volumes:
      - ../backoffice:/usr/app
      - /usr/app/node_modules
    environment:
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: db-1
      APP_KEYS: ${APP_KEYS}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      NODE_ENV: ${NODE_ENV}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1337/admin"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - strapi

  db-1:
    image: postgres:14.1-alpine
    container_name: postgres_db_1
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - db_1_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - strapi

  db-2:
    image: postgres:14.1-alpine
    container_name: postgres_db_2
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - db_2_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - strapi

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - strapi

  balancer:
    image: haproxy:2.8-alpine
    container_name: haproxy_balancer
    restart: unless-stopped
    ports:
      - "80:80"
      - "1936:1936"
    volumes:
      - ../balancer/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    healthcheck:
      test: ["CMD", "haproxy", "-c", "-f", "/usr/local/etc/haproxy/haproxy.cfg"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - strapi

networks:
  strapi:

volumes:
  db_1_data:
  db_2_data:
  pgadmin_data: